import "~/styles/globals.css";

import Link from "next/link";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <nav
          aria-label="main"
          className="flex w-auto justify-center gap-4 justify-self-start p-4"
        >
          <Link className="button" href="/input">
            Input
          </Link>
          <Link href="/drag-drop"> Drag & Drop</Link>
        </nav>

        <h1 className="text-5xl font-extrabold tracking-tight text-white ">
          File input demo
        </h1>

        {children}
      </body>
    </html>
  );
}
