import "~/styles/globals.css";

import Link from "next/link";

import { GeistSans } from "geist/font/sans";
import { Button } from "~/components/ui/button";

export const metadata = {
  title: "File input demo",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] p-8 text-white">
        <h1 className="text-5xl font-extrabold tracking-tight text-white ">
          File input demo
        </h1>

        <nav
          aria-label="main"
          className="flex w-auto justify-center gap-4 justify-self-start p-4"
        >
          <Button asChild>
            <Link className="button" href="/">
              &#9750;
            </Link>
          </Button>
          <Button asChild>
            <Link className="button" href="/input">
              Input
            </Link>
          </Button>
          <Button asChild>
            <Link href="/drag-drop">Drag & Drop</Link>
          </Button>
          <Button asChild>
            <Link href="/uploading">Uploading</Link>
          </Button>
        </nav>
        <main className="w-1/3">{children}</main>
      </body>
    </html>
  );
}
